version: "3.3"

services:
    nextjs:
        ports:
            - 4000:4000
        build:
            context: .
            dockerfile: Dockerfile.prod
        volumes:
            - /usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        env_file:
            - .env